### ISSUE TITLE
[toc2] does not work in MS Edge when notebook is large

### ISSUE THREAD

**Issue by sergei3000** [ipython-contrib/jupyter_contrib_nbextensions#1009]
When I get to a several hundred cells and some dosens headers in a notebook, the toc(2) extensions stops working in Edge. It still works in smaller notebooks.
It also works with Chrome no matter the size of a notebook.
I'm on Windows 10.

From 'About' menu:
Server Information:
You are using Jupyter notebook.
The version of the notebook server is 5.0.0 and is running on:
Python 3.6.0 |Anaconda custom (64-bit)| (default, Dec 23 2016, 11:57:41) [MSC v.1900 64 bit (AMD64)]

**Comment by jcb91** [comment]
Apologies for the delay replying to this. 

My best guess is that with a lot of cells/headings, the startup time for the toc2 nbextension gets long enough that the notebook considers it to have failed. If true, this could be prevented by using a `setTimeout` to queue the work for later execution rather than explicitly doing it as part of the load. the difference in behaviour between browsers may(?) simply be down to the efficiency of their respective javascript implementations. Do you see any logs in the 
[javascript console](http://webmasters.stackexchange.com/questions/8525/how-to-open-the-javascript-console-in-different-browsers)?

Alternatively, I have also seen notebook extensions in general fail to load when notebooks get very large, which I consider a bug with notebook (see https://github.com/jupyter/notebook/issues/2075).
If you're running into this issue, I'm afraid I don't have much of a solution :( To distinguish the two cases, do you have any other nbextensions which continue working once toc2 has stopped?

**Comment by sergei3000** [comment]
I just tried to turn on the highlighter extension.
After that I opened one of my large notebooks. And the table of contents extension started working too!
I will just continue using Chrome as it's much more stable.
I guess this can be closed now.
Thanks for your help.

**Comment by jcb91** [comment]
> I just tried to turn on the highlighter extension.
After that I opened one of my large notebooks. And the table of contents extension started working too!

Hmm, strange! Oh well, if it's working for you now, I guess we can close this, and reopen it if/when it becomes a problem again :wink:
