### ISSUE TITLE
Code_prettify does not recognize IPython magic commands

### ISSUE THREAD

**Issue by catch22** [ipython-contrib/jupyter_contrib_nbextensions#1018]
E.g., using `%%time` raises the following error, which is probably straight from PyYapf:

> [code_prettify]
> Error: SyntaxError
> invalid syntax (<unknown>, line 1)

Not sure if you feel this is a code_prettify issue or a yapf issue.

**Comment by jfbercher** [comment]
This happens because `yapf` reformats python code and the IPython magics are not recognized. So this is really a syntax error. 

It could be possible to preprocess the text from code cells to remove the magics (while leaving an anchor) and reinsert the magics after reformatting (but clearly this is not at my top todo). if somebody wants to give it a try, welcome!

**Comment by jcb91** [comment]
I've looked at this before & recall concluding that the necessary preprocessing would have to be done by the relevant kernel. The ipython kernel does this line-by-line, but I couldn't find a simple way to separate the preprocessing from the execution, iirc.

**Comment by catch22** [comment]
@jfbercher Thank you very much!
