### ISSUE TITLE
toc2 export to html issue

### ISSUE THREAD

**Issue by dsovlk** [ipython-contrib/jupyter_contrib_nbextensions#1065]
I have difficulties with "Save as html (with toc"): export to html itself works perfectly, but I can't see TOC afterwards in html file.  

In javascript  console I can see the following: 

<img width="370" alt="toc2" src="https://user-images.githubusercontent.com/31326200/29691034-63aedf18-88de-11e7-8486-ea6c463592c9.png">

[toc2] working in non-live notebook: Error: Module name "base/js/namespace" has not been loaded yet for context: _
http://requirejs.org/docs/errors.html#notloaded
    at C (require.min.js:8)
    at g (require.min.js:26)
    at toc2.js:15
    at Object.execCb (require.min.js:29)
    at $.check (require.min.js:18)
    at $.enable (require.min.js:23)
    at Object.enable (require.min.js:27)
    at $.<anonymous> (require.min.js:23)
    at require.min.js:8
    at v (require.min.js:7)

and then 

Uncaught TypeError: $(...).draggable is not a function
    at create_toc_div (toc2.js:284)
    at Object.table_of_contents (toc2.js:535)
    at Untitled22.html:14676
    at Object.execCb (require.min.js:29)
    at $.check (require.min.js:18)
    at $.enable (require.min.js:23)
    at $.init (require.min.js:17)
    at require.min.js:26

Mac OS 10.11.6, in both Chrome and Safari. Fresh installation of Anaconda
jupyter notebook --version
5.0.0

python --version
Python 2.7.13
Notebook extensions were installed with conda: 
conda install -c condo-forge jupyter_contrib_nbextensions

any help would be highly appreciated.

**Comment by jfbercher** [comment]
This is related to the end of discussion in #1032. 
I have been able to reproduce this morning. I am gonna to investigate.

**Comment by jfbercher** [comment]
Things are not really clear, but updating jqueryui cdn seems to fix this issue. 

In order to fix your installation, you should locate toc2.tpl which must reside somewhere where the python packages are installed on your system, mine is here:
`~/.local/lib/python3.5/site-packages/jupyter_contrib_nbextensions-0.2.8-py3.5.egg/jupyter_contrib_nbextensions/templates/toc2.tpl`
and replace toc2.tpl by [this one](https://raw.githubusercontent.com/jfbercher/jupyter_contrib_nbextensions/0421874e674c3fd65d2b0bd092725e8e64c88b93/src/jupyter_contrib_nbextensions/templates/toc2.tpl). Sorry, I am not familiar with Conda install.

**Comment by dsovlk** [comment]
Thanks a million @jfbercher, your solution works like a charm for me! Really appreciate such a prompt reply!
