### ISSUE TITLE
zenmode not working

### ISSUE THREAD

**Issue by elmerehbi** [ipython-contrib/jupyter_contrib_nbextensions#1075]
zenmode is among the many extensions that are listed as incompatible as per [this issue](https://github.com/ipython-contrib/jupyter_contrib_nbextensions/issues/942#issuecomment-326732524).

Also, having enabled it, it doesn't work. I cannot find the icon that used to be there before this issue.

As per @jcb91 the javascript output from a a fresh server start on a a new Firefox profile (guest) is on [pastebin](https://pastebin.com/6M6NPLc9) (faced an error uploading the file here).

**Comment by elmerehbi** [comment]
the attachement

**Comment by jcb91** [comment]
Ok, from the paste in output, I can't see anything about any nbextensions being loaded. I can only see 11 lines though, is some missing, or is that all there was? I think the notebook should log which nbextensions it attempts to load...

**Comment by elmerehbi** [comment]
Well yes because it was the browsers console.

Here's the terminal one: https://pastebin.com/aT5twbZM

The problem I guess occurs at line 239.

PS: do you face problems attaching files? I couldn't attach it here.

**Comment by jcb91** [comment]
> Well yes because it was the browsers console.

I'd expect logs about nbextensions loading in the notebook interface to show in the browser's console logs. Perhaps reload the page with the console open? Anyway, I think the server log is sufficient to diagnose for now...

> The problem I guess occurs at line 239

That line (along with the various similar ones)  show you the two locations where your nbextension files are installed: the conda-package provided install is in the sys-prefix directory at `/home/user/anaconda3/envs/py3/share/jupyter/nbextensions`, and you have a second copy of everything in the per-user directory at `/home/user/.local/share/jupyter/nbextensions`. You can probably fix this by removing the per-user install with `jupyter contrib nbextensions uninstall --user`.

However, as for zenmode not working, it doesn't actually seem to be enabled. From the server log, there should be a line similar to line 309 where the frontend requests the relevant js from the server in order to load it. However, there isn't one for zenmode, so the frontend never attempts to load it, so it (probably) isn't enabled. You can try enabling it from the CLI using

    jupyter nbextension enable --user zenmode/main

> PS: do you face problems attaching files? I couldn't attach it here.

I've never really tried, I usually just paste logs into a markdown code block (backticks!), or use a gist for larger code files as necessary. In fact, I can't say I'd even know _how_ to try attaching something...

**Comment by elmerehbi** [comment]
> `jupyter nbextension enable --user zenmode/main`

This makes it work before I remove the per-user install.

Now I removed the per-user install as you indicated and it seems to work like it used to.

Thanks for the help.

PS: For attachments, at the bottom of the reply box for an issue you can click "selecting them" or drag & drop into the reply box. I sued it with images before but with files it doesn't seem to work. But you are also restricted to text files only.

**Comment by jcb91** [comment]
Ah great, glad you've got it sorted :)

> How did I create the per-user one? Does it have to do with the environment I created?

Well, there's no way to tell for sure, but it could potentially be left over from a pre/non-conda install if you've switched, or alternatively if you've ever followed the instructions to install from the github source, I think that recommends a per-user install as default. We should probably expand the docs about where nbextensions can be!

Thanks for the attachments info too :smile:
