### ISSUE TITLE
exercise2 extension cells showing up in some notebooks but not others

### ISSUE THREAD

**Issue by satra** [ipython-contrib/jupyter_contrib_nbextensions#1079]
we have a set of notebooks with exercise2 extensions enabled. in a jupyter-hub setting or when running these through a docker container, these extension enabled cells show up in some of these notebooks but not others even though the metadata exists in the json file.

in fact in a git repo, i can use the rubberband + exercise to re-enable the view, but it doesn't make any change to the json file (since the metadata is already there). 

we are wondering if this intermittent behavior has been observed before.

**Comment by dkirkby** [comment]
I am seeing the same behavior with exercise2, but I have noticed that it correlates with longer notebooks and that the "Show Solution" widgets reappear if I delete enough cells.

I haven't tried using exercise (as opposed to exercise2) but do you know if this behavior is unique to exercise2?

**Comment by dkirkby** [comment]
@jcb91 Is this the right place to post exercise2 issues?

**Comment by jcb91** [comment]
@satra apologies, I've only just noticed this issue! @dkirkby Sure, this is the right repo for exercise/2 issues. Both exercise and exercise2 use an almost identical codebase, the only real difference is in the controls they provide (checkbox vs toggle switch), so it's unlikely that the behaviour is unique to one of them. Essentially, I think that this issue stems form the fact that both extensions only set the initial visibility of exercise solutions once, when the nbextension loads. For small notebooks, this is after the notebook has loaded, so all is well. For larger notebooks, this can happen _before_ all cells in the notebook load, and any that load after the nbextension won't get their exercises displayed correctly. It should be easy to fix, so I'll try to patch this soon.

**Comment by dkirkby** [comment]
Thanks for looking into this @jcb91!  I am using exercise2 for in-class activities in a course right now, so happy to test any patch.

**Comment by jfbercher** [comment]
You are right @jcb91. I thought that the test for notebook_fully_loaded was already implemented but it is not indeed, so the observed behaviour! 
Indeed the fix is easy as we know. 
The [display existing solution](https://github.com/ipython-contrib/jupyter_contrib_nbextensions/blob/master/src/jupyter_contrib_nbextensions/nbextensions/exercise2/main.js#L162-L189) section should be transformed into a function and called at initialization after the "wait for notebook loaded" test. 

The source is quite old now, and looking at it, it could also undergo a small lifting.
