### ISSUE TITLE
[ExecuteTime] Obtain timing results when executing notebook on command line

### ISSUE THREAD

**Issue by wstomv** [ipython-contrib/jupyter_contrib_nbextensions#1080]
Is there a way to obtain `ExecuteTime` results when running a Jupyter notebook on the command-line:
```bash
jupyter nbconvert --to notebook --execute nb.ipynb
```

or when using the `nbconvert` library through`ExecutePreprocessor` and `execute()`?

**Comment by jcb91** [comment]
Not at the moment, but it should be possible to get that functionality through extending the `ExecutePreprocessor` as you suggest...

**Comment by jcb91** [comment]
Sounds like a good feature to add

**Comment by wstomv** [comment]
Hi Josh,

I am trying to use the ExecuteTimePreprocessor in my nbtoolbelt (see PyPI.python.org).

However, it does not seem to be present in the latest version of jupyter_contrib_nbextensions.
I have version 0.3.3. installed.

What would be an appropriate way for me to try this?
And would users of nbtoolbelt get it to work.

Another thing that is probably going to come up is whether nbconvert can be convinced to show timings in generated HTML.  Any idea?

Should I create an Issue for this?

Thanks,

	Tom
- -

**Comment by jcb91** [comment]
> However, it does not seem to be present in the latest version of jupyter_contrib_nbextensions.
I have version 0.3.3. installed.

Yes, there hasn't been a release including the preprocessor yet. No real reason, just haven't got round to it. I (or someone else!) should make one soon, hopefully.

> What would be an appropriate way for me to try this?
  And would users of nbtoolbelt get it to work.

Get it from pypi/conda-forge, once there's a release that includes it. In the meantime, you could perhaps install from the github master, I guess.

> Another thing that is probably going to come up is whether nbconvert can be convinced to show timings in generated HTML.  Any idea?

I think this would require a new template and/or exporter in order to incorporate it into the html...

> Should I create an Issue for this?

Yes, probably worth a new issue :)
