### ISSUE TITLE
Collapsible Headings copy/paste issue

### ISSUE THREAD

**Issue by kjslag** [ipython-contrib/jupyter_contrib_nbextensions#1082]
With the Collapsible Headings extension enabled, copy-pasting a collapsed heading does not work.

Steps to reproduce:
1) make a heading and collapse it
2) copy the collapsed heading
3) paste it below any collapsed heading
The pasted heading (and any collapsed contents) is not displayed! However, if you save and then reload the notebook, the heading is displayed correctly.

**Comment by jcb91** [comment]
Hmm. I guess this might be something to do with the new heading cell not being rendered when it's pasted. I've managed to reproduce this on mobile, but will need to debug a little better when I get back to a desktop. Thanks for reporting!

**Comment by jcb91** [comment]
yeah, so this is because when the cell gets added, it's hidden by the (existing) heading, then when it gets rendered, the update only considers cells below the rendering one (since it assumes the cell being rendered is visible). The simplest fix is to simply always consider all cells when updating on a render event.
