### ISSUE TITLE
[toc2] changed settings not taking effect

### ISSUE THREAD

**Issue by lzkelley** [ipython-contrib/jupyter_contrib_nbextensions#1088]
When I change the settings for TOC2 they don't take effect, even after restarting the entire notebook.  For example, I turned off the skip-h1-level setting, but the h1 headers are still being ignored...  Not sure what other details would be helpful to provide.

Settings do not change even after disabling and re-enabling the extension.

I'm on jupyter 4.3.0

**Comment by jfbercher** [comment]
I think that is due to the fact that the corresponding parameter is fixed from system configuration but saved in notebook's metadat and reread from notebook's metada if present. The point is that we can not (yet) change it per notebook as the "n" or "t" links. I mentioned that before. For now, you should just edit the notebook metadata from Edit/Edit Notebook metadata and delete the relevant key.  I do not have the time from now to think to a fix. Alternatively, you can use the `title <a class='tocSkip'>` trick in #1030.

**Comment by lzkelley** [comment]
Thanks, that works.

1) `edit > edit notebook metadata`
2) manually changed the values I wanted (in this case `"skip_h1_title"` & `"toc_cell"`)
3) saved, reloaded browser window, and the changes took effect.

**Comment by jcb91** [comment]
> It seems like this is an important point that should go on the Readme, if not on the overall configurator page (if this is something that applies to many extensions

Yeah, this should have been clarified, it's my fault really for not properly thinking through  the consequences of having a per-notebook setting which doesn't have a button on the TOC panel. I guess really, we should either make the setting global, or add a button. Any thoughts as to which would be the better approach welcome! I think this should be limited to this extension, and possibly just this setting, though.

> I'll leave it open since the underlying issue still exists.

Good plan, it's best to have it open until we actually fix it, particularly as it helps people find the temporary workaround :+1:

**Comment by jcb91** [comment]
this should hopefully be fixed by #1124, if anyone gets a chance to try that PR, feedback could be very helpful :)

**Comment by jcb91** [comment]
I'm going to close this as fixed by #1124, but as always, reopen as necessary if it's not fixed!
