### ISSUE TITLE
Python Markdown: Print lists

### ISSUE THREAD

**Issue by michaelaye** [ipython-contrib/jupyter_contrib_nbextensions#1119]
Thanks for this very useful extension!

I'm wondering if it's possible to make it work with lists as well, maybe automatically adding a new line for each element?

In code, I want to be able to:
```python
l = [1,2,3]
```
```markdown
# Markdown
Current list values: {{l}}
```
but also:
```markdown
# Markdown
Beginning of list: {{l[:2]}}
```

Would that be possible? At least currently, it doesn't seem to work (mac/conda-forge up-to-date).

**Comment by jcb91** [comment]
Something like

```
#Markdown

{{ '\n * '.join(mylist) }}
```

Should work, hopefully?

**Comment by michaelaye** [comment]
So, the general unpacking from list to string works, but the `\n` is being ignored?

**Comment by jcb91** [comment]
Hmm, ok, something more complex must be going on. I'll try to have a more detailed look today...

**Comment by jcb91** [comment]
So, it's a fairly simple bug in that the js was expecting marked to wrap everything in `<p>` tags, but it doesn't wrap lists. I also fixed another bug to do with stripping tags / quotes from locations not at the start/end of the text. Unfortunately, I still have to print the output in order to avoid getting a python-style string, that is

```markdown
 #### Markdown

Beginning of list: {{ [' - {}\n'.format(item) for item in list(range(10))[:5]] }}

Beginning of list: {{ print(''.join([' - {}\n'.format(i) for i in list(range(10))[:5]])) }}
```

ends up formatted as 


<h4>Markdown<a class="anchor-link" href="#Markdown">¶</a></h4>
<p>Beginning of list: <span id="python_B9276798859046988943A7803D0C5E20_99"> - 0\n</span></p>
<p>Beginning of list: <span id="python_B9276798859046988943A7803D0C5E20_188"><ul>
<li>0</li>
<li>1</li>
<li>2</li>
<li>3</li>
<li>4</li>
</ul>
</span>

Anyway, I hope that helps a little :man_shrugging:

**Comment by jcb91** [comment]
(see #1122 for fix)
