### ISSUE TITLE
[Runtools] expands collapsed headings

### ISSUE THREAD

**Issue by SteliosStefanatos** [ipython-contrib/jupyter_contrib_nbextensions#1126]
Thanks a lot for this great nbextension! 

I noticed that when I use runtools, in particular, when I "run marked cells", and the notebook has  collapsed headings (using the "collapsible headings" extension), it will result in expanding all headings. Not a big deal, but slightly annoying :)

Using anaconda python 3, jupyter_contrib_nbextensions 0.3.1

**Comment by jcb91** [comment]
Hmm, I guess this may be because runtools selects cells before running them, though I'll have to investigate. Thanks Karen for the report!

**Comment by jcb91** [comment]
Not sure how Karen made it in there, my phone is clearly having a great day for typos :rofl:

**Comment by jcb91** [comment]
So it seems like this is caused by a combination of runtools selecting a specific cell after running all cells, and collapsible_headings' option to reveal a cell when it gets selected. I suspect we could remove the runtools selection, since it seems to just reselect the already-selected cell (and as a side effect, unselecting any cells aside from the root), though there may be a reason for it that I'm not aware of.

**Comment by jcb91** [comment]
So it seems the reason I was not aware of was that the notebook's `execute_cell(s)` methods actually alter the current selection...

**Comment by jcb91** [comment]
(and runtools does some dancing to undo the notebook's messing with selections)

**Comment by SteliosStefanatos** [comment]
Thanks @jcb91 for having a look on this!

Best,
Karen :laughing:

**Comment by juhasch** [comment]
Yes, the selections are a mess with the notebook. Thanks for digging into it.
