### ISSUE TITLE
`python-markdown` renders incorrectly when sympy.init_printing() enabled

### ISSUE THREAD

**Issue by psychemedia** [ipython-contrib/jupyter_contrib_nbextensions#1154]
If `sympy` is being used in a notebook with the `init_printing()` method enabled to support rendering of `sympy` elements, the [python-markdown](https://github.com/ipython-contrib/jupyter_contrib_nbextensions/tree/master/src/jupyter_contrib_nbextensions/nbextensions/python-markdown) extension breaks and an *end of line* is introduced before and after the substituted content.

```python
from sympy import init_printing
init_printing()

a=1.23
```

then in a markdown cell: `a is {{a}}, ok?` render as something like:

*a is*
*1.23*
*ok?*

with the *1.23* centered (presumably inherited from the `init_printing()` settings?).

**Comment by juhasch** [comment]
Looks like sympy tries to render all numbers as LaTeX. You can see this if you just execute `12345` a cell before and after executing `init_printing()`. You will see the numbers look differently.

Now what you see is a side effect of how the extension is implemented. For now you can avoid the `$` signs by typing `str(a)` instead of `a`.

**Comment by psychemedia** [comment]
Ah, thanks... hadn't spotted that trick...
