### ISSUE TITLE
Add an entry button to `/nbextensions` on notebook.

### ISSUE THREAD

**Issue by eromoe** [ipython-contrib/jupyter_contrib_nbextensions#1157]
Hello,

It is inconvenient to type `/nbextensions` , usually I forgot this  and had to search for the path name.

**Comment by jfbercher** [comment]
See perhaps "Nbextensions dashboard tab" and "Nbextensions edit menu  item"?

**Comment by eromoe** [comment]
I didn't discover there is a Nbextensions tab in  `/tree`    page .

**Comment by eromoe** [comment]
How about add this feature as default ??  Also add a button  on  notebook page .

**Comment by jcb91** [comment]
It _should_ be enabled by default, since configurator v0.2.0. I haven't bothered adding a toolbar button, since there's already a menu item, there are quite a lot of buttons already, and it's not obvious what icon would be appropriate. However, I guess it could be added fairly simply, as a non-default option. If that's something you'd like, please open an issue on the configurator repo
