### ISSUE TITLE
Printview : :error: '.' expected but ';' found.

### ISSUE THREAD

**Issue by BorderCloud** [ipython-contrib/jupyter_contrib_nbextensions#1166]
Hello

I have a bug with printview :
[main.js line 45](https://github.com/ipython-contrib/jupyter_contrib_nbextensions/blob/b9ee02d86f94015ce7eadc78266804c632d60726/src/jupyter_contrib_nbextensions/nbextensions/printview/main.js)

In the log of Jupyter, I read :
```
<console>:1: error: '.' expected but ';' found.
import os; os.system('jupyter nbconvert --to html "toree.ipynb"')
^
```
My version :

    jupyter --version
    4.4.0

Please can you fix this bug ?
Thanks

**Comment by jcb91** [comment]
Hi there. It's a little unclear what you actually did (I guess click the toolbar button provided by the printview nbextension), and which log you're referring to (browser [javascript console](http://webmasters.stackexchange.com/questions/8525/how-to-open-the-javascript-console-in-different-browsers), notebook server, kernel execution logs? I assume the last, from the message supplied).

However, I suspect that the root of this problem is that the `printview` extension is written only with a python kernel in mind, so if using any other kernel, you're likely to see syntax or other errors. What settings do you have for the various printview options? What notebook version are you running? What kernel (language, implementation and version) are you using?

Note that running

    jupyter --version

only gives the version of the `jupyter` script, which is provided by the [jupyter_core package](https://github.com/jupyter/jupyter_core), and isn't often relevant to diagnosing notebook issues. To get the _notebook_ version, use

    jupyter notebook --version

**Comment by BorderCloud** [comment]
I resolved my problem after an installation of nbconvert and its dependencies.

```
conda install nbconvert
yum install gcc gcc-c++ texlive build-essential \
    python-dev \
    unzip \
    libsm6 \
    pandoc \
    texlive-latex-base \
    texlive-latex-extra \
    texlive-fonts-extra \
    texlive-fonts-recommended \
    texlive-generic-recommended \
    texlive-xetex \
    libxrender1 \
    inkscape \
    pandoc pandoc-citeproc

yum -y install texlive-xetex-def texlive-latex-extra texlive-fonts-recommended
yum -y install 'tex(adjustbox.sty)'
yum -y install 'tex(upquote.sty)'
yum -y install 'tex(ulem.sty)'
yum -y install 'tex(euenc.def)'
yum -y install texlive-xetex-def
yum -y install 'tex(eu1enc.def)'
yum -y install 'tex(ucharclasses.sty)'
```

**Comment by jcb91** [comment]
@BorderCloud Ok, great, glad to hear you got it sorted, though still not really clear what the initial problem was from the log message. I guess then that you were attempting a conversion to latex/pdf and needed a working latex installation, as [mentioned in the readme](https://github.com/ipython-contrib/jupyter_contrib_nbextensions/blob/b9ee02d86f94015ce7eadc78266804c632d60726/src/jupyter_contrib_nbextensions/nbextensions/printview/readme.md#parameters).

Anyway, glad it's fixed. I'll close this as resolved then :smile:
