### ISSUE TITLE
Can magics be included in this project?

### ISSUE THREAD

**Issue by mdagost** [ipython-contrib/jupyter_contrib_nbextensions#1168]
I maintain a notifications magic called [jupyter-notify](https://github.com/shoprunner/jupyter-notify).  We got a request to add it to this project, but it's not clear to me from looking through the code whether pure python magics are supported, or only javascript extensions...

**Comment by jcb91** [comment]
So far, this repo contains "nbextensions", which is to say extensions to the notebook's javascript frontend. There are also a few bits of python which provide

1. scripts to allow/ease installation and activation as part of a pip/conda package
2. support for some of the js-provided functionality in nbconvert output

but these aren't really standalone things, they just support the javascript stuff, so that's presumably where the confusion arises.

To me, the main question is _why_ it might be a good idea to add magics here, which isn't clear to me from the original issue https://github.com/ShopRunner/jupyter-notify/issues/28. This repo exists mainly as a way for people to find nbextensions, and to ease their installation (which can be fiddly, currently involves making pip python packages for javascript code(!), and is just generally a headache/mess) by using a common procedure. Since magics already come with their own (python) packaging, I'm not sure there's much benefit to including them here. As I understand it, it would just remove one extra line from your pip/conda requirements :thinking: perhaps the use-case would be equally well served by

However, in principle there's no technical reason that would prevent the inclusion of magics here. My main reservation would actually be the _name_ of the repo :laughing: - since we've named it _nbextensions_ it might then be confusing for people if we start adding lots of python stuff too. but then again, the nbextension/python/kernel extension distinctions don't seem to be that obvious to most end-users anyway, so perhaps it'd be fine.

Any thoughts?

cc @juhasch @jfbercher @janschulz @nick-youngblut

**Comment by juhasch** [comment]
I agree with @jcb91's reasoning.   
Also, if you have several virtual environments,  jupyter_contrib_nbextensions are installed in the environment running the Jupyter notebook, but magics need to be installed in the environment you want to run in a notebook. I think that could lead to a lot of confusion with users. 

Also, you will need to install all dependencies of jupyter_contrib_nbextensions. This is why for IPython extensions or magics, there is https://github.com/ipython-contrib/IPython-extensions.

I think in your case, you are better off leaving it as a separate installable package.

**Comment by jcb91** [comment]
> Also, if you have several virtual environments, jupyter_contrib_nbextensions are installed in the environment running the Jupyter notebook, but magics need to be installed in the environment you want to run in a notebook.

That's a really good point. Kernel environment may be separate from server. I think that alone is enough to make keeping them separate a better idea for me.

> perhaps the use-case would be equally well served by

... This was meant to finish with "providing a conda-forge package". 🤦

**Comment by juhasch** [comment]
Adding jupyter-notify as conda-forge package sounds like a good idea to me.

**Comment by mdagost** [comment]
This all makes sense to me.  Thanks!
