### ISSUE TITLE
Proposal Add isort extension

### ISSUE THREAD

**Issue by benjaminabel** [ipython-contrib/jupyter_contrib_nbextensions#1202]
I created an [isort](https://github.com/timothycrosley/isort) extension https://github.com/benjaminabel/jupyter-isort, that I use daily. Currently it only sort imports in the current cell, but it could move all import in first code cell, and sort it. I based the implementation on  kenkoooo/jupyter-autopep8 it's my first extension, so any advice is welcome. Should I propose a PR?

**Comment by jcb91** [comment]
Sure, PRs always welcome :)

**Comment by benjaminabel** [comment]
Let's go:rocket:

**Comment by jfbercher** [comment]
Hi, actually the kenkoooo/jupyter-autopep8 nbextension was an evolution of the original [code_prettify](https://github.com/jfbercher/code_prettify). 

Together with @jcb91 we have created a library that simplifies and stengthen the development of such extensions, see [here](https://github.com/ipython-contrib/jupyter_contrib_nbextensions/tree/master/src/jupyter_contrib_nbextensions/nbextensions/code_prettify), with documentation and examples for defining a new plugin. 

For now, `code_prettify`, `autopep8`,       `2to3` extensions are defined as plugins in the framework. It would probably a good idea to use it also for `jupyter_isort` (though it works as it is, of course)

**Comment by jcb91** [comment]
Good point @jfbercher, thanks for that!

**Comment by benjaminabel** [comment]
One problem with the current implementation of `code_prettify` is that it runs prettification one cell at a time. It would be nice to do an isort and move all imports in the first code cell and currently and don't see a a way to do that in code prettify.

**Comment by jfbercher** [comment]
- I would be happy with an i-sort in each cell where imports occur (because I have use cases where it is better for the presentation that imports appear just before they are used). This and the processing of all cells in the notebook can be tackled with the library. 

- Moving all imports in the first cell is a different thing. What I would do
    - add a button and a keyboard shortcut that trig
   - a loop over all cells to grab the imports, then remove them from cells, create a cell at top, paste the imports in it and finally call isort on it. 

Something like that (for the loop)
```javascript
var imports = [];
var ind = 0;

var cells = IPython.notebook.get_cells();
cells.forEach(function(cell){
     var text = cell.get_text();
     // get imports
     var imp = text.match(/^import[\s\S]*?$/gm) 
     var from = text.match(/^from [\s\S]*? import[\s\S]*?$/gm) 
     // concat imports in current cell to the list of imports in the whole notebook
     for(var i in imp){
         imports[ind++] = imp[i]
     }
    for(var i in from){
         imports[ind++] = from[i]
     }
    // remove imports in current cell
    cell.set_text(text.replace(/^import[\s\S]*?[\r\n]/gm, '').replace(/^from [\s\S]*? import[\s\S]*?[\r\n]/gm, ''))
} 
            )
// set imports in top cell 
var c = IPython.notebook.insert_cell_at_index('code', 0)
c.set_text(imports.join('\n'))

```

**Comment by jcb91** [comment]
As @jfbercher mentions, moving all imports to the top cell is a different requirement, and would require different handling, but it might be nice to have it _in addition to_, rather than instead of, the per-cell behaviour. Given how the library works (class-based), it should be relatively easy to start with it, then subclass it, or patch an instance of it to add the whole-notebook stuff.

@jfbercher, unfortunately that regex-matching approach will break any of python's multi-line import syntaxes (e.g. parentheses, backslashes). I've been thinking about this for a while in the context of type-checking and unused-variable type prettified, which need to be aware of the  whole notebook content. I suspect that a simpler/more effective strategy might be to merge the cells together using comments as cell separators, let the isort/whatever library handle the python/other language grammar and modifications, then split it apart again into cells afterwards. However, that approach is also potentially error-prone, so I haven't implemented it yet. 🤔

**Comment by jfbercher** [comment]
> As @jfbercher mentions, moving all imports to the top cell is a different requirement, and would require different handling, but it might be nice to have it in addition to, rather than instead of, the per-cell behaviour. Given how the library works (class-based), it should be relatively easy to start with it, then subclass it, or patch an instance of it to add the whole-notebook stuff.

Yes, I agree with the "in addition to". 

> @jfbercher, unfortunately that regex-matching approach will break any of python's multi-line import syntaxes (e.g. parentheses, backslashes). 

Aah. You are right @jcb91. It will fail on multi-line imports. The merging strategy could work; but we may have something to do to keep the outputs. Not so simple.

**Comment by benjaminabel** [comment]
Thanks for your answers, and sorry for the delay. I agree with the *in addition to*, I always planed to have the two features, maybe with two keyboard shortcuts, and a isort button that would do a isort in cell by default and isort all when combined with CTRL. Also I think plugins like 2to3 could be extended with this feature.

**Comment by jcb91** [comment]
> Also I think plugins like 2to3 could be extended with this feature.

This would be pretty simple actually, just modifying the button callback to check for a modifier (perh

**Comment by jcb91** [comment]
Although perhaps `shift` might be a better  choice? I fhave a vague memory that ctrl-click might mean something on macs, but I might also just be confused...

**Comment by benjaminabel** [comment]
A simple way to treat a full notebook would be to get all cells contents adding a separator for each cell as a python comment like:
`# |$0Rŧ S€þARAŧ0R # `
Then run `isort` on the whole file with the commented separators, and then replace content of each cell with the output splitted on the ugly separator.

**Comment by jcb91** [comment]
@benjaminabel that's what I was suggesting in https://github.com/ipython-contrib/jupyter_contrib_nbextensions/issues/1202#issuecomment-359249978. Of course, the required comment syntax will vary based on language, so should possibly be added to the library config...

**Comment by benjaminabel** [comment]
Sorry I didn't read your comment with enough attention.

**Comment by jcb91** [comment]
@benjaminabel no worries :smile:

**Comment by benelot** [comment]
This seems to be done and ready. Any point in keeping the issue open?
