### ISSUE TITLE
Sub-folders scan

### ISSUE THREAD

**Issue by MYounas** [ipython-contrib/jupyter_contrib_nbextensions#1233]
Please make the search go through any level,we should be very appreciated.
Thanks.

**Comment by jcb91** [comment]
I assume you mean tree-filter? This isn't possible in the current implementation, since the notebook server only presents the contents of the current directory. So, currently, it's just a filter to limit what's displayed. If you want an actual search, it'd need to do a lot more querying of the notebook server contents API, and would lilely be relatively slow (and therefore frustrating!)
