### ISSUE TITLE
Does this work with IPython 3?

### ISSUE THREAD

**Issue by ajdroid** [ipython-contrib/jupyter_contrib_nbextensions#1282]
I've installed Ipython3 by doing:
`pip3 install ipython[all]`

Then:
`ipython3 contrib nbextension install --user`
gives:
> [TerminalIPythonApp] WARNING | File not found: 'contrib'

**Comment by jcb91** [comment]
> Does this work with IPython 3?

I guess you mean IPython on python3 (since IPython current version is 6.3.1). Yes, this repo should work fine on python 3, but it seems like you've got a bit confused about the install process. The commands you want are

    pip3 install jupyter_contrib_nbextensions

To install the python package, then

    jupyter contrib nbextensions install --user

To copy the css & javascript to the correct place (note the command begins `jupyter`, not `ipython3`).

**Comment by ajdroid** [comment]
Thanks!
