### ISSUE TITLE
Duplicate entries "Python Markdown" and "python-markdown"

### ISSUE THREAD

**Issue by wuffi** [ipython-contrib/jupyter_contrib_nbextensions#1292]
After installation with `jupyter contrib nbextension install`, I had a hard time using the "Python Markdown" extension:
As I only realized after quite a bit of testing, I also chose the entry "python-markdown" in the browser.
Upon choosing the "Python Markdown" entry, everything was working perfectly right away and I removed the "python-markdown" item.  
I would have found it helpful, if there wouldn't have been a "python-markdown" item. Is there an explanation where it could come from?

**Comment by jcb91** [comment]
@wuffi so to clarify, you did `jupyter contrib nbextension install`, then looked at the configurator page/tab to enable python markdown, but later realised that there were two slightly different entries, only one of which worked? My best guess is that the non-working variant was created by a command like `jupyter nbextension enable python-markdown`. In this case, the key is simply written to the config file, even if the specified name can't be found (though you should see a warning in such a case). Thanks configurator will then assume that the nbextension in question exists, simply because it's been enabled. To avoid such a situation, check output of any enable commands run from a shell. That's my best guess, unless I've misunderstood the problem 🤷

**Comment by wuffi** [comment]
Thank you so much for your answer. I think this is exactly what happened.
Since the cause of the issue was a invalid entry from user side, I would also close the issue.
In the long run, it might be helpful for inexperienced users like me to have a more verbose message in the web configurator to avoid confusion.
Again, thanks a lot for your help. I am happy to have the extensions working now, because they are really helpful.
