### ISSUE TITLE
[Select CodeMirror Keymap] Feature request: A redo shortcut for Emacs keymap

### ISSUE THREAD

**Issue by dschaehi** [ipython-contrib/jupyter_contrib_nbextensions#1331]
I like and use the Emacs keymap a lot. What I miss is a 'redo' shortcut: somehow the Emacs keymap suppresses the existing 'redo' shortcut (i.e., Ctrl-Shift-Z or Cmd-Shift-Z) by the default keymap and does not provide an alternative. Under emacs one would press Ctrl-g and then press Ctrl-Shift-Minus to redo changes. This does not work with the Emacs keymap.

**Comment by aiguofer** [comment]
Hey @dschaehi, sorry I had not checked for issues in a long time (the problem with a massive repo full of contributions). The problem was that CodeMirror assigns 'redo' to Ctrl-Y by default, which gets used for yank. I've gone ahead and added this to the extension and will create a PR with CodeMirror to see if it makes sense to add this there by default.
