### ISSUE TITLE
Code formatting?

### ISSUE THREAD

**Issue by janschulz** [ipython-contrib/jupyter_contrib_nbextensions#365]
I just found http://www.cleancss.com/python-beautify/, so code formatting is posisble in javascript. This as a button or a hotkey would be great, especially if it would work with the line length plugin.

**Comment by jcb91** [comment]
Love this idea. Will look into it.

**Comment by jcb91** [comment]
So, on further investigation, it's not so easy to just use the code behind your example (which seems to be  based on [beautify-web/js-beautify](github.com/beautify-web/js-beautify), since at heart it's a javascript reformatter (with extensions for CSS and HTML). It doesn't cope with, for example,
* comments(!)
* decorators using the `@decorator` syntax
* the functions call syntax, e.g. `myfunction(*args, **kwargs)`
plus probably other things too.

While it would be possible to write a javascript-only formatter, it'd be quite a lot of effort from scratch. Something like normalising numbers of newlines between functions etc might be easy to do from scratch? Python seems (to me) to have quite a complex grammar though, so I don't know how complicated it might become.

**Comment by JanSchulz** [comment]
:-(

The other way would be to open a new kernel, load a python beautifier (https://github.com/google/yapf) and open a new channel to get cleanup requests.

**Comment by jcb91** [comment]
yep, something like `yapf` would be possible, but it then becomes a requirement of the extension, I guess, which may get confusing for people trying to use it. Possible though, I think.

**Comment by jcb91** [comment]
On the other hand, I did also find [SecPlus/pep8.js](github.com/SecPlus/pep8.js), which spots pep8 violations without fixing them, so that might be worth adapting

**Comment by mraxilus** [comment]
I would very much be interested in an extension which does something similar to yapf.

**Comment by jfbercher** [comment]
Attempted an extension in #724 . 
Hope it will help!

**Comment by jcb91** [comment]
closing as fixed by #724, #726
