### ISSUE TITLE
How can I contribute to the table of content extension?

### ISSUE THREAD

**Issue by cqcn1991** [ipython-contrib/jupyter_contrib_nbextensions#480]
I thought about build a toc extension, but then found here is one. Personally, I want to add a few tweaks to it, but don't know about the workflow working with building extensions for Ipython Notebook

Is there any instruction of it?
Addtionally, I find writing html inside js is intimidating, is it possible to extract it out?

**Comment by jcb91** [comment]
(see also comments on #471)

There isn't really a build process for the majority of extensions, which are frontend-only (they are just javascript/css, and don't have server-side python extensions). They're basically just collections of static files installed in an appropriate location.

I'd say extracting html-writing out is a little trickier than writing it in an extension using jquery. I mainly write stuff in jquery as it looks nicer to me & is simpler to edit later. But, of course, that's all subjective.
For minimum js, you could write your html outside your javascript files, then copy it in as a js string (see, for example, the large block at [nbextensions/usability/highlighter/highlighter.js#L209-L219](https://github.com/ipython-contrib/IPython-notebook-extensions/blob/master/nbextensions/usability/highlighter/highlighter.js#L209-L219))?

If you really wanted to include, say, an html file in your extension's main js file, you could make an AJAX request to grab it, but at some point you'll still have to use javascript to insert it into the DOM, and that, combined with the jquery AJAX, seems like more trouble than learning enough jquery to find/insert elements...

**Comment by cqcn1991** [comment]
@jcb91 Thanks alot! I'm not sure if you have work with `Ruby on Rails` or `PHP` before, I just want something like `.erb`, something like:

```
<div class="table-of-content">
  <%= title.each do |title| %>
    <h1><%= title.content %></h1>
  <% end  %>
</div>
### Then you declare component's behavior below.
```

which I can use `for loop` to generate `html` etc. Writing it in all `js` is quite hard for me.

**Comment by jcb91** [comment]
@cqcn1991 no worries. I see what you mean, it's always easier to work with what's familiar. The main problem is that RoR & PHP are both server-side technologies, while the notebook extensions are mainly limited to client-side scripting. Additionally, with something like erb, you'd need to write the whole page, no? It becomes complicated to insert that into the main notebook page, which is rendered by a python tornado server. Modifying the main tornado server would equally be complicated, and liable to break things, so I'd not consider it worthwhile. Additionally, you need to get hold of the headings somehow, and since these can change in the browser before they're saved on disk, essentially you need to use the notebook's javascript API to get the headings. I fear a little javascript may be unavoidable.

As for your example, this kind of thing is done in [nbextensions/usability/toc/main.js#L27-L67](https://github.com/ipython-contrib/IPython-notebook-extensions/blob/91fa78f9761bff01fd7ca7cc3769fc39d3b39e1a/nbextensions/usability/toc/main.js#L27-L67). That example is mainly using individual jquery calls to do things like:
 * select elements: `$('#toc-wrapper .hide-btn')` the `$` is a short name for jQuery, and the call uses a css-type specification to select all elements with the class 'hide-btn' with an ancestor that has id 'toc-wrapper'
 * set selected elements attributes or text: `.attr('title', 'Show ToC')` sets the selected element(s) title attribute(s) to 'Show ToC', while `.text('[+]')` sets the element's inner text.
You could use something like codepen or jsfiddle to mess around and learn a bit of jquery to make html elements and the like - see for example http://codepen.io/jcb91/pen/rxENBR for a pen ready set up with the correct jquery, bootstrap, css etc. The css tab has the toc css in it.

**Comment by jcb91** [comment]
And, as with many things, the quickest way to get what you want form the existing toc/toc2 is probably to make a copy, and then fiddle with it!

**Comment by juhasch** [comment]
I agree with @jcb91. I don't think there is an easy way to do it differently within a notebook.

**Comment by jfbercher** [comment]
Welcome @cqcn1991. I agree with @jcb91 and @juhasch. You should make a copy of current toc2, eg as mytoc, then edit the name in toc2.yaml; use the nbextensions tab to diable toc2, enable mytoc and then start playing with the code. The extension is reloaded each time  you reload the jupyter-notebook (just reload the page). You shall use the javascript console to look at what happens.

**Comment by cqcn1991** [comment]
@jcb91 @juhasch @jfbercher Thanks for all your help. Didn't expect you guys are so helpful. I now has a copy to `toc2` working, Hope I'll have something to share with you soon.

**Comment by juhasch** [comment]
The notebook will only load `main.js` (or however you name your main file). You can load more js files using a `require` command. Take a look at other extensions how this is done.

**Comment by halflings** [comment]
Just a suggestion (for the future maybe): even without using server-side technology, you can still have templating to make it easier to maintain extensions that render relatively complex HTML code like the ToC. handlebars.js is a good example (has support for loops, conditions, etc.)

http://handlebarsjs.com/builtin_helpers.html

**Comment by cqcn1991** [comment]
@halflings thanks alot for this. May try this for sometime. Someone also told me other template as well. Now I'm experimenting TOC with `ReactJS`, but now I'm having problem in loading the modules (I don't know require js beforehand).

**Comment by cqcn1991** [comment]
Hi, @jcb91 @jcjaskula @jfbercher 
Here is what I want to do with `toc`, to make it into sidebar (toggle), because I feel it is a missing feature of the Ipython Notebook itself. A quick look of what I've done so far:

![qq](https://cloud.githubusercontent.com/assets/2425141/13396847/c07c7c6c-df31-11e5-827e-ebe5c8fe14d2.png)

Originally, I though about re-write the code first,using something like ReactJS maybe. However, it is far beyond my limit. So I thought about just starting with css, to show you guys what I want to do with `toc`, and later may find others to cooperate with me.

**Comment by jcb91** [comment]
@cqcn1991 you seem to have more or less got it done already! Or is that just a photo mockup?

**Comment by jfbercher** [comment]
It looks nice! 
Immediately some options come to mind: it would be great to have options to dock/undock (let it float as now) the toc and to dock either on the right or on the left side. Also it would be nice if the sidebar can be resized.

**Comment by jcb91** [comment]
The `usability/help_panel` extension implements something similar, with a dockable, resizable, side panel, so you might look at the js & css for that for inspiration.

**Comment by cqcn1991** [comment]
@jcb91 It's easy to get quick and dirty with css and jquery, but the code is simply unmaitainable(I simply delete some of the original functionality to make the code not that long).

**Comment by jcb91** [comment]
@cqcn1991 I see what you mean. ToC2 in particular is a bit daunting, even compared to other extensions. I've got a branch cleaning it up a bit which I started to see how it worked, which might be easier to look at: [toc2_cleanup](https://github.com/jcb91/IPython-notebook-extensions/tree/toc2_cleanup)

**Comment by cqcn1991** [comment]
@jcb91 And it also bothers me that the extension all bundled together. I can see it benefit in putting all discussion together, but it also makes it hard to make PR, I think.

**Comment by jcb91** [comment]
@cqcn1991 I don't quite understand. It's still quite possible to make a PR affecting only a single nbextension, if that's what bothers you? Or perhaps I've misunderstood?

**Comment by cqcn1991** [comment]
@jcb91 Yes, it's possible. I just think if there is both seperation and combination would be better. Seperated repo would be easier for people to participate, combined repo would be easier for people to use.

**Comment by jcb91** [comment]
closing as stale
