### ISSUE TITLE
Instructions for installation via CLI

### ISSUE THREAD

**Issue by joequant** [ipython-contrib/jupyter_contrib_nbextensions#678]
Are there instructions for installing a particular extension via CLI?  Thanks.

**Comment by jcb91** [comment]
That depends on exactly what you mean by installing a particular extension. If you want to install the javascript, css, etc files for *only* a single one of the extensions from this repo *without* installing any of the others, then it's a little bit convoluted, as there aren't individual packages for most of them (with the exceptions of [scratchpad](https://github.com/minrk/nbextension-scratchpad), [tree-filter](https://github.com/jdfreder/jupyter-tree-filter), [split-cell-to-notebook](https://github.com/captainsafia/split-cell-to-notebook), to my knowledge, plus possibly others that I'm unaware of independent packages for). Unfortunately for the rest of the nbextensions, although you can install only a single one of them, you'll have to download the whole repository in order to get the ones you want. For example:

    git clone https://github.com/ipython-contrib/IPython-notebook-extensions.git ipc-nbe
    jupyter nbextension install ipc-nbe/nbextensions/usability/collapsible_headings

note however that this will install the extensions without the first part of the path usually included by this repository (in this example, to `collapsible_headings` rather than `usability/collapsible_headings`). You equally could do something similar with github archives (zip files) or tarballs if you don't have/want to use `git`, but I'd need to know what platform you're on in order to give more specific instructions on that.

If you're happy to have all the extensions' files installed (but not used), and are actually just looking for a way to *enable* a single extensions (i.e. ensure it's loaded every time a notebook opens) then you can use `jupyter nbextension enable` with the appropriate `require` string, e.g. `usability/collapsible_headings/main` for the collapsible headings extension.

**Comment by jcb91** [comment]
@joequant did you get what you needed for this issue?

**Comment by joequant** [comment]
Yes.  I think that answered my question.  Thanks.
