### ISSUE TITLE
confusion wrapped in confusion regards installation

### ISSUE THREAD

**Issue by ndc33** [ipython-contrib/jupyter_contrib_nbextensions#695]
I would like to install the extensions on series 4x based on conda installation. I am however completly confused. The following do not seem to be consistent.
* https://github.com/ipython-contrib/jupyter_contrib_nbextensions/wiki/Home-4.x-(Jupyter)
* https://github.com/ipython-contrib/jupyter_contrib_nbextensions
* various recipies found on internet
for naming we have nbextensions, jupyter_contrib_nbextensions, not to mention the conda nb extensions. 

since most involve PIP i wonder if they are relevant to conda.
A year ago i vaguely remember a simple install with a control/selection panel for activation. 
If someone could point to a method of installation i would be very grateful.

**Comment by jcb91** [comment]
Apologies, there is indeed a great deal of confusion currently.

> If someone could point to the real nbextensions

As mentioned previously, there isn't a 'real' nbextensions. nbextenions are effectively javascript plugins for the notebook environment, and as such there are a lot of different ones. There are standalone ones, such as https://github.com/jcb91/jupyter_highlight_selected_word (a standalone nbextension providing highlighting of instances of the currently-selected word), and there are also multiple independent collections of nbextensions (this repo is one collection of lots of different nbextensions collected together for ease of installation/use, while https://github.com/Anaconda-Platform/anaconda-nb-extensions is a collection of a few (about 5?) nbextensions which provide functionality related to `conda`. It is perfectly possible to install any and all of the above at the same time.

> since most involve PIP i wonder if they are relevant to conda.

Essentially most point to pip because they don't yet have conda recipes. `conda` coexists quite happily with (indeed, includes) `pip`. If an nbextension mentions a conda installation method, use that. If not, just use pip/whatever they recommend.

The first two (this repo's main readme, and the wiki page) conflict because we've just made a major restructure, and haven't yet updated the wiki. Ignore the wiki for now, I hope to address this shortly.

The main jupyter documentation will tell you about installing single nbextensions which each consist of a few javascript and css files. The docs for this repo are slightly different, because we package lots of nbextensions together inside a python package, and also include extras like nbconvert classes and templates. `jupyter_contrib_nbextensions` is a python package containing lots of `nbextensions`.

**Comment by ndc33** [comment]
thanks
i dived in and followed https://github.com/ipython-contrib/jupyter_contrib_nbextensions using PIP
it installed but had validation issues regarding missing yaml files.

since we now have a chain of: installs, enabling, activations, dashboards (/nbextensions), seperate install instructions in 4.x  specifying the requirement of adding scripts, and everybody using non keyword friendly (unique identity) package names i cannot say i understand anything. Im going to regard this as "under construction" and come back later. Its a shame the steps taken for transition to npm have made such a mess.

**Comment by jcb91** [comment]
> had validation issues regarding missing yaml files.

Could you elaborate?

> since we now have a chain of: installs, enabling, activations, dashboards (/nbextensions)

nbextensions have always required (and will always require) a separate install vs enable step; this is not new. There has been some confusion in terminology with enabling/activating, but they refer to the same thing. The dashboard is a convenience, so that people don;t have to deal with the CLI every time they want to enable/disable an nbextension. You don't have to use it if you don't want to.

> seperate install instructions in 4.x specifying the requirement of adding scripts

I don't understand what you mean here - could you explain?

> non keyword friendly (unique identity) package names

I guess you mean it'd be nicer to have something easily google-able? I'd agree, I was going to use `themysto` (from [themisto](https://en.wikipedia.org/wiki/Themisto_(moon))). Unfortunately, it turns out that that caused confusion too (nobody had any idea what it was meant to be).

**Comment by jcb91** [comment]
Our new conda-forge recipe should take care of a simple one-command install & activate, with
