### ISSUE TITLE
Align Environment can't work with latex_envs extnesion

### ISSUE THREAD

**Issue by shanhaiying** [ipython-contrib/jupyter_contrib_nbextensions#720]
The latex environments such as align,align*, aligned, split etc. can't work well in theorem, lemma etc. latex environments.

Such as 
`\begin{theorem}
$$
\begin{aligned}
f(x)&=\chi_{A_i}(x)\\
=&g(x)
\end{aligned}
$$
\end{theorem}
`
![image](https://cloud.githubusercontent.com/assets/1595652/17609882/89813160-606b-11e6-9fa5-a449de3b1f59.png)

If we change code as the following:
`\begin{theorem}
$$
\begin{aligned}
f(x)&=\chi_{ A_i}(x)\\
=&g(x)
\end{aligned}
$$
\end{theorem}`

It works well.

![image](https://cloud.githubusercontent.com/assets/1595652/17610005/93a4eb36-606c-11e6-8571-d1d5a78cac62.png)

**Comment by jcb91** [comment]
I don't really follow what's changed from the first code example to the second?

**Comment by jfbercher** [comment]
There is an extra whitespace. 
This is linked to the _{A_i which may be interpreted as markdown emphasis. I will look at it.

**Comment by jfbercher** [comment]
I have included a quick fix in commit https://github.com/ipython-contrib/jupyter_contrib_nbextensions/pull/714/commits/a7b3168bf0a455fbe329dee3d89c268d183ce879 lines 143-144 (the full PR #714 is pending for now - you may just copy the two lines). 
 
This is a bit ad-hoc for now. Actually the problem comes from the fact that `latex_envs` enable to mix markdown and $\LaTeX$ in environnements. Markdown was replaced in the formula, resulting in the replacement of `\\` by a single  `\`.  

I have to find a better way to do that because it might subsist other issues. Have a small idea of a way to go, but it will lead to refactor many things.

**Comment by jfbercher** [comment]
This is solved in the `latex_envs` version provided in #746.
Issue can be closed.
