### ISSUE TITLE
Unrecognized JSON config file version, assuming version 1

### ISSUE THREAD

**Issue by pybokeh** [ipython-contrib/jupyter_contrib_nbextensions#727]
I get this warning message when launching jupyter notebook server:
Unrecognized JSON config file version, assuming version 1

Installed everything via pip.  I have explicitly set the location of the notebook config directory and data directory.

**Comment by jcb91** [comment]
Hi there. This warning isn't really anything to worry about, but I can understand it's annoying.

This happens when a json config file (e.g. `jupyter_notebook_config.json`) is created without a `version` key. This is avoided in the install script for the nbconvert config by explicitly setting the version to 1 (see https://github.com/ipython-contrib/jupyter_contrib_nbextensions/blob/e106161a04bee18e79b9ef16d23e6edc176d73be/src/jupyter_contrib_nbextensions/install.py#L86-L87), but it looks as though in moving to use the jupyter-provided nbextension install, I forgot to do the same for the notebook config. To be honest, I feel like the jupyter commands should also set a default config version for new files, but, hey, can't have it all I guess. I'm currently in the middle of attempting to rescue my half-dead laptop, so can't easily submit a PR, but you're welcome to roll one yourself, if you've time :smile:

**Comment by juhasch** [comment]
See also https://github.com/jupyter/notebook/issues/1480
Should be resolved with new traitlets release.
