### ISSUE TITLE
Some problem about  latex_envs

### ISSUE THREAD

**Issue by shanhaiying** [ipython-contrib/jupyter_contrib_nbextensions#731]
1. latex_envs extension do not support nested enumerate environment.

![image](https://cloud.githubusercontent.com/assets/1595652/18031491/922806c0-6d15-11e6-92c0-c9aaa746a120.png)

![image](https://cloud.githubusercontent.com/assets/1595652/18031493/a3523a24-6d15-11e6-9003-9b1979d1f872.png)
1. latex_envs can not work for  "\right}".

![image](https://cloud.githubusercontent.com/assets/1595652/18031480/4c7561ea-6d15-11e6-8c59-e04061a5b790.png)
![image](https://cloud.githubusercontent.com/assets/1595652/18031485/6a9cfdea-6d15-11e6-8193-b27eb64b89d5.png)

**Comment by jfbercher** [comment]
- The fact that it was not possible to nest several environments of the same type was a known limitation, mentioned in the doc, due to the fact that js regular expression are not suited for recursive things. 
- The second problem was linked to an issue in accounting for markdown markup within $\LaTeX$ environments.

I have developped a solution to the recursivity problem, namely a bunch of specialized "regex"-like functions that enable to find/extract nested structures. This in turn also enabled to solve the second problem from ground, I think.  There are also several improvements in the exporter to latex and html and elsewhere. 

This gives a *major update* that you can find at https://github.com/jfbercher/jupyter_latex_envs
Installation instructions are in the README there (the Pypi version is not  ready yet).  Give it a try and make comments/ specific issues [there](https://github.com/jfbercher/jupyter_latex_envs/issues). The full documentation is [here](https://rawgit.com/jfbercher/jupyter_latex_envs/master/src/latex_envs/static/doc/latex_env_doc.html). 


![image](https://cloud.githubusercontent.com/assets/7596356/18135896/c08f22f6-6fa3-11e6-9b03-5136391aad54.png)

**Comment by shanhaiying** [comment]
After the update of latex_envs,   a new problem arises.

`\begin{thm}
aa $$bb$$ cc
\end{thm}`

![image](https://cloud.githubusercontent.com/assets/1595652/18175509/1f587f34-70a4-11e6-8dee-cb5ed01b4d04.png)

**Comment by jfbercher** [comment]
Thanks for testing all that. 
Please make new issues at https://github.com/jfbercher/jupyter_latex_envs. 
Fixed.

**Comment by jcb91** [comment]
@jfbercher would it be worth trying to move towards removing the duplicated latex_envs code from this repo, and simply specify your repo as a pip dependency?

**Comment by jfbercher** [comment]
Yes, this is a good idea.

**Comment by jfbercher** [comment]
The issue is solved in the `latex_envs` version provided in #746.
Issue can be closed.
