### ISSUE TITLE
Codefolding in iPython 5.1

### ISSUE THREAD

**Issue by Fleckenteufel** [ipython-contrib/jupyter_contrib_nbextensions#761]
Codefolding can not be activated in iPython 5.1. It says it is "possibly incompatible".

**Comment by jcb91** [comment]
this is just because the compatibility is listed as 4.x in codefolding's [configurator yaml file](https://github.com/ipython-contrib/jupyter_contrib_nbextensions/blob/1dc9596af4f8976ee54ee0973f1f041346a91ba2/src/jupyter_contrib_nbextensions/nbextensions/codefolding/codefolding.yaml#L7), presumably because nobody has tested it with notebook 5.x dev versions yet. You can still enable it by unchecking the box marked 'disable configuration for extensions without explicit compatibility' on the configurator page/tab. Then, if it works correctly for you, let us know here (0r with a PR), and we can update the yaml file.

**Comment by Fleckenteufel** [comment]
Thanks. I tried it and it seems to work fine with iPython 5.1.0.
