### ISSUE TITLE
Extensions/templates directories not created

### ISSUE THREAD

**Issue by azjps** [ipython-contrib/jupyter_contrib_nbextensions#783]
Apologies if I an misunderstanding how the jupyter data directory is supposed to get set up now. As of 199bfe27 I do not seem to have an `extensions` or `templates` directory created in `jupyter_data_dir()` when running `setup.py install` or `pip install` (either from github master tarball or local clone). When running `jupyter contrib nbextension install --user` all of the `nbextensions` are copied as expected. As a consequence, I get a 404 attempting to navigate to `<notebook url>/nbextensions`.

When I rollback to 89109b4b9, `setup.py install` does indeed print some stuff about setting up the `extensions` and `templates` directories and I am able to successfully navigate to `<notebook url>/nbextensions`.

Am I missing some configuration step in master?

**Comment by jcb91** [comment]
> I do not seem to have an `extensions` or `templates` directory created in `jupyter_data_dir()`

Yes, this is expected. Since we now have a fully pip-compatible package `jupyter_contrib_nbextensions`, these items now live in the python `site-packages` directory, as part of the pip package, and as a result aren't copied to the jupyter data directory on install of the repo. Pre/postprocessors and exporters can now be imported using their fully-qualified names. You can find the extensions stuff with the following python snippet:

```python
import jupyter_contrib_nbextensions.nbconvert_support
print(jupyter_contrib_nbextensions.nbconvert_support.__all__)
print(jupyter_contrib_nbextensions.nbconvert_support.templates_directory())
```

> As a consequence, I get a 404 attempting to navigate to `<notebook url>/nbextensions`

This is (as a result of the new install process mentioned above) for a different reason. At a guess, probably down to the flags used in the install. The `jupyter contrib nbextension install --user` command should add configuration files to use the `jupyter_nbextensions_configurator` to jupyter notebook config files for the current user. Assuming the notebook server is run as the same user, that should be sufficient. If you're attempting to have a multi-user install of the repo, you may wish to consider the alternative flags of `--sys-prefix`, which writes to config files in the python `sys.prefix` jupyter config directories, or the `--system` flag, which causes system-wide config files to be written (you will probably require admin rights to write to the system-level config files).

Does (any of) that make sense?

**Comment by azjps** [comment]
Yes, that makes total sense. I had gotten confused by following months-old discussions on the issue tracker.

I'm still not sure why I had been getting a 404 when trying to view the `nbextensions/` page on the same user for which I ran `jupyter contrib nbextension install --user`. But using `--sys-prefix` (and setting `c.NotebookApp.server_extensions = ["jupyter_nbextensions_configurator"]` for other users) works like a charm.

**Comment by jcb91** [comment]
> I'm still not sure why I had been getting a 404 when trying to view the `nbextensions/` page on the same user for which I ran `jupyter contrib nbextension install --user`

Well, the python distribution which provides the `jupyter notebook` command must also be the same one for which the `pip install ...` process was performed, so that the `jupyter_nbextensions_configurator` python serverextension is installed in the correct `site-packages` directory. At any rate, glad you got it working :)
