### ISSUE TITLE
Configuration Editor shows double entries 

### ISSUE THREAD

**Issue by sniperlucian** [ipython-contrib/jupyter_contrib_nbextensions#800]
Symptoms:

double entries  (repeating all over ... see pic)

![image](https://cloud.githubusercontent.com/assets/18550683/20635469/afefce0c-b35d-11e6-88aa-a4521ca67ba3.png)

Environment:

Reinstalled Anaconda after several issues. Maybe old config floating around?

**Comment by jcb91** [comment]
Yep, this is likely down to duplicate installs in two different locations. Jupyter nbextensions can in general be installed in several places - see [the jupyter_path function in jupyter_core.paths](https://github.com/jupyter/jupyter_core/blob/7e944323082f66f345736b68dad44f8a3691a812/jupyter_core/paths.py#L42-L69) for details. To fix the double-install, simply run the uninstall command for whichever installation you wish to remove. Since you're running in conda, I'd recommend keeping an install in sys.prefix, and removing others, in order to stick neatly with the environment isolation conda provides. To uninstall a user copy:

    jupyter contrib nbextension uninstall --user

and possibly the system-wide ones as well:

    jupyter contrib nbextension uninstall --system

(though that may need admin privileges to write to system-level jupyter dirs, not sure on windows).

If the above doesn't work, the configurator serverextension should give warning logs about where duplicate files are found.

As a matter of interest, the possible install locations are, briefly:

- user's jupyter data dir, on Windows `~\.jupyter`
- python `sys.prefix` jupyter data dir, in `sys.prefix + /share/jupyter/nbextensions`
- system-wide jupyter data dir, OS-dependent, but in Windows 7, I think they should be in `~\AppData\jupyter\nbextensions`

To find all possible paths, you can use the jupyter command:

    jupyter --paths

**Comment by jcb91** [comment]
Also, the fact that they show up as double entries implies that you have an older version of the configurator, which you should be able to check with

    jupyter nbextensions_configurator --version


The newer configurator versions should show a single entry for each
You can upgrade with pip

    pip install --upgrade jupyter_nbextensions_configurator

or conda

  conda update jupyter_nbextensions_configurator

as appropriate.

**Comment by jcb91** [comment]
@sniperlucian did you manage to resolve this ok?

**Comment by sniperlucian** [comment]
thx for pickup .. actually not, there are my results:

- conda doesnt know about "jupyter_nbextensions_configurator"
- pip upgrades it too:  0.2.3
- trying to uninstall, I get following errors:

**>>jupyter contrib nbextension uninstall --user
>>jupyter contrib nbextension uninstall --system**

> [JupyterContribApp] CRITICAL | Bad config encountered during initialization:
> [JupyterContribApp] CRITICAL | Unrecognized flag: **_'--user'  * or '--system' *_**


**running without --user or --system I get:**

> Please supply at least one subcommand:

**Comment by sniperlucian** [comment]
ok - made a new install on laptop to compare and finally got rid of the old configs. 

The trick was to delete the files in:

`>c:\users\name\.jupyter\*`

(which didn't do much actually), but also the **data** directory: 

`>c:\users\name\appdata\roamning\jupyter\*   (except 'running')`

quite confusing, that you need to delete the **data** dir to clear the config. ;)

**Comment by jcb91** [comment]
> quite confusing, that you need to delete the *data* dir to clear the config. ;)

Yeah, it can be confusing, especially when they start to get muddled together like here. The rationale is that you aren't actually clearing any config. The configurator searches through the the notebook server's nbextensions path (which  includes any subdirectories of the jupyter data directories named `nbextensions`), where it looks for yaml files which declare configurable nbextensions' existence, but don't actually store any config. The config itself *is* stored in jupyter config directories. The double let entries came from nbextensions which had been installed in two different data directories. Hope that makes sense, as you say, it is far from intuitive! Anyway, glad you got it sorted!
