### ISSUE TITLE
'Disable all' button

### ISSUE THREAD

**Issue by ggrrll** [ipython-contrib/jupyter_contrib_nbextensions#849]
Hi,

It could be useful to add a button 'disable all' - to check incompatibility, restore configurations , etc...

Thanks.

**Comment by juhasch** [comment]
I believe this is better handled by the notebook itself. There already is an issue for this:
https://github.com/jupyter/notebook/issues/1992

**Comment by ggrrll** [comment]
so, should I close this one?

**Comment by jcb91** [comment]
I'm not sure these are quite the same thing - jupyter/notebook#1992 references disabling all config, which would also handle serverextensions, and seems to be talking about when the server is run. What @ggrrll seems to be requesting (if I understand correctly?) is for a button on the configurator page which does the same thing as clicking all the nbextensions' disable buttons individually would. This would be possible, but and might be useful, depending on what you were hoping for. Additionally, because of how the config API works (read-from-all, write-to-one), the configurator only ever edits the per-user config, so again, its utility would depend on what you wanted to do in the first place, and @juhasch may be right that the notebook iteslf might be a better place to look for a solution. If you still think a button on the configurator page would be useful, feel free to open an issue on the [Jupyter-contrib/jupyter_nbextensions_configurator](https://github.com/Jupyter-contrib/jupyter_nbextensions_configurator) repo.

**Comment by ggrrll** [comment]
well yes, that's what  I have in mind: a simple button that prevents me to un-check  all the extensions manually - don't know if that's also what @juhasch has in mind

**Comment by juhasch** [comment]
My feeling is that the intended use-case (checking incompatibilities) the notebook itself is the right place. 

I have no objections against adding a "reset" button for the extensions. The question is then: Do we disable only the contrib extensions or all extensions ?

**Comment by ggrrll** [comment]
I don't know much...my idea is to easily control the ones that appear in the [configurator](https://github.com/Jupyter-contrib/jupyter_nbextensions_configurator)

**Comment by jcb91** [comment]
> my idea is to easily control the ones that appear in the configurator

Ok, well that's definitely possible, and not very difficult. I'll add an issue there & think about it at some point...
