### ISSUE TITLE
List of extensions is not sorted in documentation

### ISSUE THREAD

**Issue by juhasch** [ipython-contrib/jupyter_contrib_nbextensions#852]
This is the list of extensions from [Read-the-docs](http://jupyter-contrib-nbextensions.readthedocs.io/en/latest/nbextensions.html):

    (some) LaTeX environments for Jupyter notebook
    A 2to3 converter
    Addbefore
    jupyter-autopep8
    autosavetime
    autoscroll
    Chrome Clipboard
    Code Font Size
    A Code Prettifier
    Codefolding
    Collapsible Headings
    Comment/Uncomment
    Help menu entry
    Datestamper
    Drag and Drop
    MathJax Equation Numbering
    Execute Time
    Exercise
    Exercise2 extensions
    Freeze
    Gist it
    Help Panel
    Hide Input
    Hide all Input
    Highlight selected word
    Highlighter
    Hinterland
    Options
    init_cell
    Keyboard shortcut editor
    QT Console
    Limit Output
    Move selected cells
    Navigation Hotkeys
    nbTranslate – helps translating notebooks – provides multilanguage support
    Notebook web notifications
    Printview
    Python Markdown
    Rubberband
    Ruler
    Runtools
    Scratchpad notebook extension
    ScrollDown
    Search and Replace
    Select CodeMirror Keymap
    SKILL for Codemirror
    Skip traceback
    Jupyter notebook snippets menu
    Basic menu customization
    Advanced menu customization
    Troubleshooting
    TODO
    Reasons for using this extension
    Spellchecker
    Split Cells
    Table of Contents (2)
    Table Beautifier
    Toggle all line numbers
    Tree-filter
    Zenmode

I guess we should sort it...

**Comment by jcb91** [comment]
It is sorted, but perhaps not by name? I can't recall how...

**Comment by juhasch** [comment]
I think we sort the filenames.
Some on the list are no extensions at all. For example in `snippets_menu` there are several `#` headers.

**Comment by jcb91** [comment]
Right. Good idea to fix, at any rate!

**Comment by juhasch** [comment]
#853 fixes `snippets_menu`

**Comment by jcb91** [comment]
right, so this is marginally more complicated than I thought, in that the list is currently sorted by the name key from the yaml file (see [docs/source/autogen_scripts/autogen_nbextensions_list.py#L48-L50](https://github.com/ipython-contrib/jupyter_contrib_nbextensions/blob/c43120c2b102811dbb501a97bca7be66893e8c97/docs/source/autogen_scripts/autogen_nbextensions_list.py#L48-L50)), but the link text is I think set by sphinx using the main header in the linked document. I suspect the best solution is to generate the toctree rst directly, using the yaml-specified names (since this is what eveyrone will see in the configurator) rather than using the toctree sphinx helper...

**Comment by juhasch** [comment]
Yes, this is how it looks to me, too. I think taking the name from the yaml file makes it more robust.

**Comment by jcb91** [comment]
ok, I think I've managed to implement this ok in #875
