### ISSUE TITLE
ExecuteTime doesn't seem to deal well with time zones

### ISSUE THREAD

**Issue by tonycpsu** [ipython-contrib/jupyter_contrib_nbextensions#904]
I enabled ExecuteTime, and noticed that I was getting execution times of 5 hours plus whatever it took to actually run the cell.  The server's time zone is UTC and the client's is in EST, so naturally I suspected a time zone problem.

A quick look at the source for ExecuteTime suggests that it's subtracting start_time from end_time.  Looking at my cell metdata, I note that ```start_time``` shows a "Z" for zulu time, but ```end_time``` does not.

Hacking ExecuteTime.js to just add a "Z" to end_time fixes the problem, but I don't know enough about where the end_time is coming from or if it's time-zone-aware or anything like that to say that this is a good fix.  I just thought I'd raise the issue here, as I expect other people running clients and servers with different time zones will face this same issue.

**Comment by jcb91** [comment]
Timezone issues have come up before for certain combinations of kernels and server/kernel/browser timezones - see, https://github.com/ipython-contrib/jupyter_contrib_nbextensions/issues/549#issuecomment-199406193 for an explanation.

ExecuteTime gets its timestamps as follows:

1. cell is queued for execution by the browser, nbextension sets `start_time` using the moment.js library. This is an ISO8601 timestamp in UTC, so will end in a `Z` for 'zero offset' (see the wiki article https://en.wikipedia.org/wiki/ISO_8601#UTC)
2. On receiving an `execute_reply` message, the `end_time` is set from the message's `header.date` timestamp. This is where problems can start, as depending on the kernel implementation, this timestamp may be in local time, without a timezone specified. however, the nbextension has no way of knowing whether or not this is the case if the timezone of the stamp isn't specified. I raised this with jupyter_client, and it looks like it's recently been fixed: https://github.com/jupyter/jupyter_client/issues/143. 
3. The `start_time` is updated from the `execute_reply` message's `metadata.started` timestamp, in order to get more accurate timings by using the kernel-provided timestamps for everything. This also fixes problems with kernel/client timezone differences, since the kernel provides both values from the same timezone. __However__, the metadata.started value isn't part of the required Jupyter message spec, and so _not all kernels implement it_.

I guess we could add a configurable 'default kernel timezone', as an assumption for what to use if the kernel timestamps are timezone unaware? The potential pitfall there of course is that different kernels may use different conventions, e.g. one using un-specified UTC, another using unspecified local time...

**Comment by jcb91** [comment]
I've attempted to address this in #907 with a configurable option. Hope it helps.

**Comment by tonycpsu** [comment]
Just had a chance to pull down the changes and try this out, and it works perfectly.  Thanks!

**Comment by bigtonylewis** [comment]
I'm still having this problem, using release 0.2.6.  I've tried it with and without the "Display times in UTC, rather than in the local timezone set by the browser" setting set

**Comment by jcb91** [comment]
@bigtonylewis there's been a fix added since 0.2.6, in #934. Could you try that?

**Comment by bigtonylewis** [comment]
Thank you, yes it works
