### ISSUE TITLE
ExecutionTime is using UTC time for start but local time for finish ?

### ISSUE THREAD

**Issue by themrmax** [ipython-contrib/jupyter_contrib_nbextensions#933]
I'm in AEDT (UTC+11) and getting the following behaviour:

![image](https://cloud.githubusercontent.com/assets/8220288/24433198/c6192a36-1472-11e7-8a3b-bc8a468b780f.png)

Any ideas what could be causing this?

I'm on a new Macbook Pro, Sierra 10.12.3, running Anaconda Python 3.6

**Comment by themrmax** [comment]
meh fixed it by disabling this option in the configurator
![image](https://cloud.githubusercontent.com/assets/8220288/24439119/ea02ef0c-1497-11e7-8f56-47c5f38c4c5b.png)

**Comment by jcb91** [comment]
Hi, thanks for mentioning this, as it does actually seem to need fixing, by applying the default timezone to both start & end. I encountered this myself recently, after switching to BST. However, altering start and end will just change the problem so that it looks like everything happened (in your case) 11 hours ago :expressionless:. Unfortunately the real source of this problem is kernel inconsitencies. The assume-UTC option arose from #904, where the kernel was using a UTC timestamp (which is what they should be doing), but *without specifying the timezone* (which is less ok, as it was causing momentjs to assume local tz). However, the kernels we we are using (mine is IPython kernel 4.4.0 on python 3.6) seem to be returning *local* timestamps *without a specified timezone*, which is not what they should be doing at all. This has been fixed in jupyter_client 5.0.0dev (see https://github.com/jupyter/jupyter_client/commit/fd05171a94bd6431df0b48f280f9027934b58d98), but remains a problem at least until that gets into master, and potentially after that as other kernels may continue to do weird things...
