### ISSUE TITLE
select_keymap with breaks markdown cell soft wrapping

### ISSUE THREAD

**Issue by singletS** [ipython-contrib/jupyter_contrib_nbextensions#960]
Soft word/line wrap in markdown cells stops working when select_keymap extension is used to select emacs map (haven't checked the other maps).  

Disabling the select_keymap plugin in the configurator returns normal wrap behavior but, alas, no emacs bindings.

Using jupyter-emacskeys (found via the select_keymaps readme) works, providing (a few) emacs bindings without breaking wrapping.

conda env with notebook 5.0

**Comment by jcb91** [comment]
Sounds odd. I'm not immediately familiar with this nbextension, so can't think of an obvious reason that this might be happening. I think @aiguofer was the author for this?

**Comment by jcb91** [comment]
actually, on closer inspection, this seems to be semi-intentional. Using `select_keymap` overrides the default CodeMirror lineWrapping option with its own `select_keymap_line_wrap` option, which is declared in yaml to default to `true`, but in actual javascript, just remains `undefined` unless set, so gets interpreted as `false` by default. As a temporary fix, you should be able to get around this by using the configurator to set the option false, then back to true to re-enable line wrapping. I'll look at implementing defaults correctly in the javascript too, though.

**Comment by aiguofer** [comment]
Ahh, interesting issue! Thanks for fixing that Josh. I hadn't noticed since I use disable line wrap in mine.

I believe I added that based on `jupyter-emacskeys` but decided to make it an option in case others didn't want it (like me)

**Comment by jcb91** [comment]
> I hadn't noticed since I use disable line wrap in mine 

This kind of thing has happened to me a few times, I'm regularly bitten by breaking something I don't personally use 🤣
