### ISSUE TITLE
Scratchpad incompatible

### ISSUE THREAD

**Issue by psinger** [ipython-contrib/jupyter_contrib_nbextensions#999]
I am using an updated anaconda environment and set-up nbextensions successfully. Unfortunately, the only extension I really want to have, is greyed out with the statement "possibly incompatible".

Any idea how to resolve that? Thanks.

**Comment by jcb91** [comment]
Related: #942. Many nbextensions are marked as potentially incopatible just because they haven't been fully tested with notebook 5.x. However, most of them will still work fine. The configurator has a checkbox just under its heading (above the filter box) which allows you to enable and configure nbextensions even if they aren't explicitly marked as compatible with the notebook version you're running. You can try scratchpad by unchecking the box, then if it seems to work ok for you (or doesn't!), it would be helpful if you could report that back here, and we can update either the compatibility listing, or the extension code as necessary.

Does that make sense?

**Comment by jfbercher** [comment]
Just tried it. It seems to work fine.

**Comment by jcb91** [comment]
great, thanks @jfbercher. I'll PR another compatibility update...

**Comment by jcb91** [comment]
fixed by #1000
